### PR TITLE
Feature/replace makefile with cmake and conan

### PR DESCRIPTION
**Pull request by Baldurius**
The original Makefile made some assumptions about the system that caused issues:
- dependencies had to be installed system-wide
- linker was instructed to link to -lglfw3 instead of -lglfw
- there were some "-framework" arguments that are not supported by recent compilers/linkers

This patch replaces the manually created Makefile with a combination of the CMake Makefile generator and the conan2 package manager. This way, all external dependencies can be resolved without the need for system-wide installation and building the project becomes more robust.

For further instructions, see the new section "How To Build" in the README.md.

### CODE REVIEW

**Comment by ShoYamanishi** [comment]
@Baldurius Thanks for bringing it to a much better shape with the latest Linux state of affair. I guess Conan is widely available in many distros? The changes look good and I'll try to grab a linux machine shortly and test it.

**Comment by Baldurius** [comment]
@ShoYamanishi Yes, conan is available for all operating systems and can target any build platform. It requires python though. But that should be widely available.

Personally, I only used it with Linux. Build instructions should be the same for any OS, but I never tested it.

**Comment by ShoYamanishi** [comment]
@Baldurius I have got a chance to run it on Ubuntu 22.04.1 LTS/AMD Ryzen and I think I need your further help on the following issues.
1. **Installing missing x-related packages.**
I had to manually install the following packages, as conan generated errors 
even with `-c tools.system.package_manager:mode=install`:

```
sudo apt install libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libfontenc-dev libxaw7-dev libxkbfi\
le-dev libxmu-dev libxmuu-dev libxpm-dev libxres-dev libxss-dev libxt-dev libxv-dev libxvmc-dev libxcb-render-util0-dev libxcb-xkb-dev li\
bxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xiner\
ama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev
```
They require the root privilege. Do you know how to handle those issues? I'd like to avoid those manual installation of packages, as they are probably platform-specific.

2. **Installing libgd**
It seems [libgd](https://libgd.github.io/) has to be manually downloaded and built (at least on Ubuntu).
Do you know of any automated way to handle it as a package? If not, then I'll add some comments like following after merging the pull request.

```
$ wget https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.gz
$ gunzip libgd-2.3.3.tar.gz
$ tar xvf libgd-2.3.3.tar
$ cd libgd-2.3.3
$ mkdir build
$ cd build
$ ../configure
$ make
$ sudo make install

```

If you have any thoughts or further updates, that would be great. If not, then it'll be ok. I'll merge the requests anyway, and then add some installation instruction for libgd (and possibly those X-related packages as Ubuntu specific instruction.)

**Comment by ShoYamanishi** [comment]
Closing this as I have updated the repo with the better installation process with CMake at 7b01203.
Thanks for your contribution anyway.

**Pull request closed without merging**
